package icu.samnyan.aqua.sega.chunithm.model.gamedata;

/**
 * @author samnyan (privateamusement@protonmail.com)
 */
public enum Genre {
    POPS_ANIME("POPS & ANIME"),
    RESERVE("Reserve"),
    NICONICO("niconico"),
    TOUHOU("東方Project"),
    RESERVE2("Reserve2"),
    ORIGINAL("Original"),
    VARIETY("Variety"),
    IRODORI("イロドリミドリ"),
    KOTONOHA("言ノ葉Project"),
    GEKIMAI("ゲキマイ"),
    TEAM("チーム限定"),
    A11(""),
    A12(""),
    A13(""),
    A14(""),
    A15(""),
    A16(""),
    A17(""),
    A18(""),
    A19(""),
    A20(""),
    A21(""),
    A22(""),
    A23(""),
    A24(""),
    A25(""),
    A26(""),
    A27(""),
    A28(""),
    A29(""),
    A30(""),
    A31(""),
    A32(""),
    A33(""),
    A34(""),
    A35(""),
    A36(""),
    A37(""),
    A38(""),
    A39(""),
    A40(""),
    A41(""),
    A42(""),
    A43(""),
    A44(""),
    A45(""),
    A46(""),
    A47(""),
    A48(""),
    A49(""),
    A50(""),
    A51(""),
    A52(""),
    A53(""),
    A54(""),
    A55(""),
    A56(""),
    A57(""),
    A58(""),
    A59(""),
    A60(""),
    A61(""),
    A62(""),
    A63(""),
    A64(""),
    A65(""),
    A66(""),
    A67(""),
    A68(""),
    A69(""),
    A70(""),
    A71(""),
    A72(""),
    A73(""),
    A74(""),
    A75(""),
    A76(""),
    A77(""),
    A78(""),
    A79(""),
    A80(""),
    A81(""),
    A82(""),
    A83(""),
    A84(""),
    A85(""),
    A86(""),
    A87(""),
    A88(""),
    A89(""),
    A90(""),
    A91(""),
    A92(""),
    A93(""),
    A94(""),
    A95(""),
    A96(""),
    A97(""),
    A98(""),
    UNDEFINE("全ジャンル"),
    CRYSTALPLUS("官譜追加"),
    LUNATIC("LUNATIC"),
    FANMADE("創作譜面");


    private String displayName;

    Genre(String displayName) {
        this.displayName = displayName;
    }

    public String displayName() {
        return displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
