CREATE TABLE mai2_user_playlog_new
(
	id INTEGER,
	achievement INTEGER NOT NULL,
	after_delux_rating INTEGER NOT NULL,
	after_grade INTEGER NOT NULL,
	after_grade_rank INTEGER NOT NULL,
	after_rating INTEGER NOT NULL,
	before_delux_rating INTEGER NOT NULL,
	before_grade INTEGER NOT NULL,
	before_rating INTEGER NOT NULL,
	break_critical_perfect INTEGER NOT NULL,
	break_good INTEGER NOT NULL,
	break_great INTEGER NOT NULL,
	break_miss INTEGER NOT NULL,
	break_perfect INTEGER NOT NULL,
	character_awakening1 INTEGER NOT NULL,
	character_awakening2 INTEGER NOT NULL,
	character_awakening3 INTEGER NOT NULL,
	character_awakening4 INTEGER NOT NULL,
	character_awakening5 INTEGER NOT NULL,
	character_id1 INTEGER NOT NULL,
	character_id2 INTEGER NOT NULL,
	character_id3 INTEGER NOT NULL,
	character_id4 INTEGER NOT NULL,
	character_id5 INTEGER NOT NULL,
	character_level1 INTEGER NOT NULL,
	character_level2 INTEGER NOT NULL,
	character_level3 INTEGER NOT NULL,
	character_level4 INTEGER NOT NULL,
	character_level5 INTEGER NOT NULL,
	combo_status INTEGER NOT NULL,
	deluxscore INTEGER NOT NULL,
	fast_count INTEGER NOT NULL,
	hold_critical_perfect INTEGER NOT NULL,
	hold_good INTEGER NOT NULL,
	hold_great INTEGER NOT NULL,
	hold_miss INTEGER NOT NULL,
	hold_perfect INTEGER NOT NULL,
	is_achieve_new_record bit not null,
	is_break bit not null,
	is_clear bit not null,
	is_critical_disp bit not null,
	is_deluxscore_new_record bit not null,
	is_event_mode bit not null,
	is_fast_late_disp bit not null,
	is_freedom_mode bit not null,
	is_hold bit not null,
	is_new_free bit not null,
	is_play_tutorial bit not null,
	is_slide bit not null,
	is_tap bit not null,
	is_touch bit not null,
	late_count INTEGER NOT NULL,
	level INTEGER NOT NULL,
	login_date INTEGER NOT NULL,
	max_combo INTEGER NOT NULL,
	max_sync INTEGER NOT NULL,
	music_id INTEGER NOT NULL,
	place_name varchar(255) null,
	played_music_level1 INTEGER NOT NULL,
	played_music_level2 INTEGER NOT NULL,
	played_music_level3 INTEGER NOT NULL,
	played_user_id1 INTEGER NOT NULL,
	played_user_id2 INTEGER NOT NULL,
	played_user_id3 INTEGER NOT NULL,
	played_user_name1 varchar(255) null,
	played_user_name2 varchar(255) null,
	played_user_name3 varchar(255) null,
	player_num INTEGER NOT NULL,
	score_rank INTEGER NOT NULL,
	slide_critical_perfect INTEGER NOT NULL,
	slide_good INTEGER NOT NULL,
	slide_great INTEGER NOT NULL,
	slide_miss INTEGER NOT NULL,
	slide_perfect INTEGER NOT NULL,
	sync_status INTEGER NOT NULL,
	tap_critical_perfect INTEGER NOT NULL,
	tap_good INTEGER NOT NULL,
	tap_great INTEGER NOT NULL,
	tap_miss INTEGER NOT NULL,
	tap_perfect INTEGER NOT NULL,
	total_combo INTEGER NOT NULL,
	total_sync INTEGER NOT NULL,
	touch_critical_perfect INTEGER NOT NULL,
	touch_good INTEGER NOT NULL,
	touch_great INTEGER NOT NULL,
	touch_miss INTEGER NOT NULL,
	touch_perfect INTEGER NOT NULL,
	track_no INTEGER NOT NULL,
	type INTEGER NOT NULL,
	user_play_date varchar(255) null,
	vs_mode INTEGER NOT NULL,
	vs_rank INTEGER NOT NULL,
	vs_status INTEGER NOT NULL,
	vs_user_achievement INTEGER NOT NULL,
	vs_user_grade_rank INTEGER NOT NULL,
	vs_user_name varchar(255) null,
	vs_user_rating INTEGER NOT NULL,
	playlog_id INTEGER NOT NULL,
	version INTEGER NOT NULL,
	is_photo_upload BOOLEAN NOT NULL,
    user_id bigint references mai2_user_data (id) ON DELETE CASCADE,
    PRIMARY KEY (
         id
    )
);
INSERT INTO mai2_user_playlog_new (
id,
achievement,
after_delux_rating,
after_grade,
after_grade_rank,
after_rating,
before_delux_rating,
before_grade,
before_rating,
break_critical_perfect,
break_good,
break_great,
break_miss,
break_perfect,
character_awakening1,
character_awakening2,
character_awakening3,
character_awakening4,
character_awakening5,
character_id1,
character_id2,
character_id3,
character_id4,
character_id5,
character_level1,
character_level2,
character_level3,
character_level4,
character_level5,
combo_status,
deluxscore,
fast_count,
hold_critical_perfect,
hold_good,
hold_great,
hold_miss,
hold_perfect,
is_achieve_new_record,
is_break,
is_clear,
is_critical_disp,
is_deluxscore_new_record,
is_event_mode,
is_fast_late_disp,
is_freedom_mode,
is_hold,
is_new_free,
is_play_tutorial,
is_slide,
is_tap,
is_touch,
late_count,
level,
login_date,
max_combo,
max_sync,
music_id,
place_name,
played_music_level1,
played_music_level2,
played_music_level3,
played_user_id1,
played_user_id2,
played_user_id3,
played_user_name1,
played_user_name2,
played_user_name3,
player_num,
score_rank,
slide_critical_perfect,
slide_good,
slide_great,
slide_miss,
slide_perfect,
sync_status,
tap_critical_perfect,
tap_good,
tap_great,
tap_miss,
tap_perfect,
total_combo,
total_sync,
touch_critical_perfect,
touch_good,
touch_great,
touch_miss,
touch_perfect,
track_no,
type,
user_play_date,
vs_mode,
vs_rank,
vs_status,
vs_user_achievement,
vs_user_grade_rank,
vs_user_name,
vs_user_rating,
playlog_id,
version,
is_photo_upload,
user_id
)
SELECT id,
achievement,
after_delux_rating,
after_grade,
after_grade_rank,
after_rating,
before_delux_rating,
before_grade,
before_rating,
break_critical_perfect,
break_good,
break_great,
break_miss,
break_perfect,
character_awakening1,
character_awakening2,
character_awakening3,
character_awakening4,
character_awakening5,
character_id1,
character_id2,
character_id3,
character_id4,
character_id5,
character_level1,
character_level2,
character_level3,
character_level4,
character_level5,
combo_status,
deluxscore,
fast_count,
hold_critical_perfect,
hold_good,
hold_great,
hold_miss,
hold_perfect,
is_achieve_new_record,
is_break,
is_clear,
is_critical_disp,
is_deluxscore_new_record,
is_event_mode,
is_fast_late_disp,
is_freedom_mode,
is_hold,
is_new_free,
is_play_tutorial,
is_slide,
is_tap,
is_touch,
late_count,
level,
login_date,
max_combo,
max_sync,
music_id,
place_name,
played_music_level1,
played_music_level2,
played_music_level3,
played_user_id1,
played_user_id2,
played_user_id3,
played_user_name1,
played_user_name2,
played_user_name3,
player_num,
score_rank,
slide_critical_perfect,
slide_good,
slide_great,
slide_miss,
slide_perfect,
sync_status,
tap_critical_perfect,
tap_good,
tap_great,
tap_miss,
tap_perfect,
total_combo,
total_sync,
touch_critical_perfect,
touch_good,
touch_great,
touch_miss,
touch_perfect,
track_no,
type,
user_play_date,
vs_mode,
vs_rank,
vs_status,
vs_user_achievement,
vs_user_grade_rank,
vs_user_name,
vs_user_rating,
0,
0,
0,
user_id FROM mai2_user_playlog;

ALTER TABLE mai2_user_playlog RENAME TO bak_mai2_user_playlog;
ALTER TABLE mai2_user_playlog_new RENAME TO mai2_user_playlog;

CREATE TABLE mai2_user_photo_log
(
    id INTEGER,
    place_id INTEGER NOT NULL,
    upload_date      varchar(255) null,
    playlog_id INTEGER NOT NULL,
    track_no INTEGER NOT NULL,
    user_id bigint references mai2_user_data (id) ON DELETE CASCADE,
    PRIMARY KEY (
         id
    )
);

CREATE TABLE mai2_user_portrait
(
    id INTEGER,
    user_id INTEGER NOT NULL,
    div_number INTEGER NOT NULL,
    div_length INTEGER NOT NULL,
    div_data VARCHAR null,
    place_id INTEGER NOT NULL,
    client_id  VARCHAR(255)  null,
    upload_date  VARCHAR(255)  null,
    file_name  VARCHAR(255)  null,
    PRIMARY KEY (
        id
    )
);

CREATE TABLE mai2_user_session
(
    id INTEGER NOT NULL,
    start_date varchar(255) null,
    user_id bigint references mai2_user_data (id) ON DELETE CASCADE,
    PRIMARY KEY (
         id
    )
);